# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Pipr::WS"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

timeout: 20

plugins:
    Thumbnail:
        cache: /var/cache/pipr/thumb_cache
        compression: 7
        quality: 100

cache_dir: '/var/cache/pipr/cache'

restrict_targets: 1

sites:
  demo:
     sizes: [ '100x', '100x100', '200x', '300x', '144x82', '50x50', '76x55', '300x50', '169x169' ]
     allowed_targets: [ 'public/images/test' ]
  rg:
     sizes: [ '110x90', '230x200', '711x470', '93x70', 'x470', '980x', '980x400', '966x' ]
     allowed_targets: [ 'http' ]
     replacements: [ [ 'www\.kuoni-cmp\.com', 'www.dercmp.com' ] ]
  test:
     sizes: [ '30x30', '100x30', '30x', 'x30' ]
     allowed_targets: [ 'public/images/empty.jpg', 'public/images/test.png', 'non-existing-image', 'http://dghasdfguasdfhgiouasdhfguiohsdfg/non-existing-image' ]
    
log_path: .
log_file: pipr-ws_app.log
logger_format: %U [%P] %L @%D> %m in %f l. %l

allow_local_access: 1

